# This creates a deployment with 4 replicas.
# It uses nginx:1.7.9 image and the deployment
# is named 'nginx-deployment-prod'
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-prod
spec:
  replicas: 4
  template:
    metadata: 
      labels:
        app: nginx-deployment-prod
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
